## This configures a demo app that 
## generates random logs 
demo:
  app:
    create: true
    name: demo-app
    namespace: default
    labels:
      app: go-app

## Parseable LogStore config
parseable_server:
  url: "http://parseable.parseable.svc.cluster.local"
  username: "parseable"
  password: "parseable"

## collector config
kube_collector:
  logStreams:
    - name: demoapp
      collectInterval: 10s
      collectFrom: 
        namespace: default
        podSelector: 
          app: go-app
      labels:
        language: go
        version: 1.2.6

## collector deployment configuration
image:
  repository: parseable/collector
  pullPolicy: Always
  tag: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []
